language: scala
jdk:
  - openjdk8
  - openjdk11
  - openjdk15
scala:
   - 2.12.12
   - 2.13.5
script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
